/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ca.mcgill.ecse.flexibook.application;

import ca.mcgill.ecse.flexibook.model.FlexiBook;
import ca.mcgill.ecse.flexibook.model.User;
import ca.mcgill.ecse.flexibook.persistence.FlexiBookPersistence;
import ca.mcgill.ecse.flexibook.view.BusinessPage;


public class FlexiBookApplication {
	private static FlexiBook flexibook;
	private static User currentUser;
	
    public String getGreeting() {
        return "Hello world.";
    }
	
	public static void main(String[] args) {
		 System.out.println(new FlexiBookApplication().getGreeting());
		 // TODO: Swap for start page
		boolean isOwnerTest = false; // temp for testing
		java.awt.EventQueue.invokeLater(() -> new BusinessPage(isOwnerTest).setVisible(true));
	}
	
	public static FlexiBook getFlexibook() {
    	if (flexibook == null) {
    		//flexibook = new FlexiBook();
			flexibook = FlexiBookPersistence.load();
    	}

		return flexibook;
	}

	public static User setCurrentUser(User aUser) {
		currentUser = aUser;
		return currentUser;
	}
	public static User getCurrentUser() {
		return currentUser;
	}
}
 
